### ISSUE TITLE
hof adhoc generator not working with absolute paths

### ISSUE THREAD

**Issue by newbeelearn** [hofstadter-io/hof#106]
OS: Linux ubuntu 20.04
Shell: bash

I am trying to use adhoc generator to generate some code with following command
hof gen /scripts/configs/chartapijson.cue -T /scripts/templates/chartgen.go -O /scripts/out/
it gives following error
[Named template "/scripts/templates/chartgen.go" not found for AdhocGen /scripts/templates/chartgen.go AdhocGen templates: []]
while initializing adhoc generator
same command works if i use relative path for template

any idea what could be wrong?

**Comment by verdverm** [comment]
hmm, I will take a look, there have been lots of filepath edge cases with the revamp and upgrade to that part of the system.

I uncovered a different, but similar looking error upstream in CUE https://github.com/cue-lang/cue/issues/1908

This looks different and is probably a bug in hof, around how template lookup happens. Without looking into it yet, I'm assuming that I will need some extra logic for detecting and handling absolute paths, around the path vars on gen.Runtime/Generator

I'm planning a new release this week, so good timing!

dev note: add a test

**Comment by verdverm** [comment]
@newbeelearn this should now be fixed in https://github.com/hofstadter-io/hof/commit/a4de42fb3dc99d6a06acf9f8859f955f2a7fd712

It's going to pull off the directories of the template name and place it under the output dir with the same name (unless you set the name with `=` in `-T`

Please reopen this issue if it does not work for you. (by compiling or waiting for the next release)
